name: first worflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: ehco "hello"
      - name: printing bye
        run: echo "Bye"
      
  
        
